config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts
  # You can have the root of your site routed with "root"
  root 'welcome#index'
  resources :podcasts, only: [:index, :show]

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay) }
  end

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    @podcasts = Podcast.all.order("Created_at DESC")
  end

  def show
    @podcast = Podcast.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<% if alert %>
  <p class="alert">
    <%= alert %>
  </p>
<% elsif notice %>
  <p class="notice">
    <%= notice %>
  </p>
<% end %>

<!--Header File-->
<header id="main_header" class="cf">
  <div class="wrapper_wide">
    <%= link_to 'Podcast.fm', root_path, id: "logo" %>
      <nav>
        <ul>
          <% unless podcast_signed_in? %>
          <li><%= link_to "Explore", podcasts_path %></li>
          <li><%= link_to "Sign In", new_podcast_session_path %></li>
          <li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
          <% else %>
          <li><a href="#">Dashboard</a></li>
          <li><%= link_to "Explore", podcasts_path %></li>
          <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete  %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>
    <%= yield %>
  </body>
</html>

app/views/podcasts/index.html.erb
<div id="banner" class="podcasts_banner">
      <h1>Discover your new favorite podcast</h1>
    </div>

    <div class="cf" id="podcasts">
      <div class="wrapper">
        <ul>
          <% @podcasts.each do |podcast| %>
            <%= link_to podcast do %>
              <li>
                <img src="img/narwhal-podcast.jpg" alt="Narwhal Podcast"/>
                <div class="podcast_overview">
                  <h2><%= podcast.title %></h2>
                  <p class="episode_count">1 Episode</p>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>

app/views/podcasts/show.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <% unless @podcast.itunes.blank? %>
        <a href="<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
      <% end %>
      <% unless @podcast.stitcher.blank? %>
      <a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
      <% end %>
      <% unless @podcast.podbay.blank? %>
      <a href="<%= @podcast.podbay %>" class="subscribe_link">Podbay</a>
      <% end %>
    </div>
  </div>
  <div id="breadcrumbs">
    <%= link_to podcasts_path do %>
      All Podcast
      <span>/</span>
      The Rocketship Podcast
    <% end %>
  </div>
   <div id="episodes">
     <div class="wrapper_skinny">
       <ul class="cf">
         <li class="cf">
           <div class="episode_thumbnail">
             <a href="episode.html">
               <img src="img/sohai.jpg" alt="Sohai Rehan">
             </a>
           </div>
           <div class="episode_overview">
             <h2><a href="episode.html">How to Pull Off 12 (Well Executed) Startups in 12 Month</a></h2>
              <p class="description">Sohai ali is founder of anything which rehan have and one day she will became my heart one day i hold her hand and walk in a world most expensive street.</p>
           </div>
         </li>

         <li class="cf">
           <div class="episode_thumbnail">
             <a href="episode.html">
               <img src="img/sohai.jpg" alt="Sohai Rehan">
             </a>
           </div>
           <div class="episode_overview">
             <h2><a href="episode.html">How to Pull Off 12 (Well Executed) Startups in 12 Month</a></h2>
              <p class="description">Sohai ali is founder of anything which rehan have and one day she will became my heart one day i hold her hand and walk in a world most expensive street.</p>
           </div>
         </li>

         <li class="cf">
           <div class="episode_thumbnail">
             <a href="episode.html">
               <img src="img/sohai.jpg" alt="Sohai Rehan">
             </a>
           </div>
           <div class="episode_overview">
             <h2><a href="episode.html">How to Pull Off 12 (Well Executed) Startups in 12 Month</a></h2>
              <p class="description">Sohai ali is founder of anything which rehan have and one day she will became my heart one day i hold her hand and walk in a world most expensive street.</p>
           </div>
         </li>

         <li class="cf">
           <div class="episode_thumbnail">
             <a href="episode.html">
               <img src="img/sohai.jpg" alt="Sohai Rehan">
             </a>
           </div>
           <div class="episode_overview">
             <h2><a href="episode.html">How to Pull Off 12 (Well Executed) Startups in 12 Month</a></h2>
              <p class="description">Sohai ali is founder of anything which rehan have and one day she will became my heart one day i hold her hand and walk in a world most expensive street.</p>
           </div>
         </li>
       </ul>
     </div>
   </div>
  </div>
    <div class="paginations">
      <span class="previous_page disabled">Previous</span>
        <em class="current">1</em>
        <a href="#">2</a>
        <a class="next_page" href="#">Next</a>
    </div>

app/views/welcome/index.html.erb
<div id="background">
  <header class="cf">
    <div class="wrapper_wide">
      <a href="#" id="logo">Podcast.fm</a>
        <nav>
          <ul>
            <% unless podcast_signed_in? %>
            <li><%= link_to "Explore", podcasts_path %></li>
            <li><%= link_to "Sign In", new_podcast_session_path %></li>
            <li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
            <% else %>
            <li><a href="#">Dashboard</a></li>
            <li><%= link_to "Explore", podcasts_path %></li>
            <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete  %></li>
            <% end %>
          </ul>
        </nav>
      </div>
  </header>
      <div class="wrapper_skinny">
        <h1>Discover your new favorite <br> podcast, or create your own.</h1>
        <%= link_to "Create a Podcast", new_podcast_registration_path, class: "button1 button_highlight" %>
        <%= link_to "Explore", podcasts_path, class: "button1 button_white" %>
      </div>
    </div>